---
- name: Check all the facts
  debug:
    msg: "Package: {{ __docker_install_name }}, Is 17.03: {{ __docker_17_03 }}"

# Fixme: this should be in ansible or another role
- name: Install yum versionlock
  yum:
    name:
      - yum-plugin-versionlock

- name: Install Docker 17.03 on CentOS/Redhat
  when: __docker_17_03
  yum:
    name:
      - "docker-ce-selinux-{{ docker_package_version }}"
      - "{{ __docker_install_name }}"
      - containerd.io
    conf_file: "{{ docker_yum_config }}"
    state: "{{ docker_package_state }}"
  notify:
    - restart docker
    - lock docker package

- name: Install Docker on CentOS/Redhat
  when: not __docker_17_03
  package:
    name:
      - "{{ __docker_install_name }}"
      - containerd.io
    state: "{{ docker_package_state }}"
  notify:
    - restart docker
    - lock docker package
