---
- name: restart docker
  ansible.builtin.service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - docker_service_manage | bool
    - not (docker_rootless | bool)

- name: Restart rootless docker
  ansible.builtin.systemd_service:
    name: docker
    scope: user
    state: "{{ docker_restart_handler_state }}"
  listen: restart docker
  become: true
  become_user: "{{ docker_rootless_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ docker_rootless_runtime_dir }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path={{ docker_rootless_runtime_dir }}/bus"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - docker_service_manage | bool
    - docker_rootless | bool

- name: Restart cAdvisor
  ansible.builtin.systemd_service:
    name: cadvisor
    state: "{{ docker_cadvisor_restart_handler_state }}"
    daemon_reload: true
  listen: restart cadvisor
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - docker_cadvisor_service_manage | bool
    - docker_cadvisor_state == 'started'

- name: apt update
  ansible.builtin.apt:
    update_cache: true
