---
- name: Restart Docker socket (Debian/Ubuntu system packages).
  ansible.builtin.service:
    name: docker.socket
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - docker_service_manage | bool
    - ansible_facts.os_family == 'Debian'
    - not docker_add_repo | bool
  listen: restart docker

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool

- name: apt update
  ansible.builtin.apt:
    update_cache: true
